[package]
name = "stabilizer-ch-form-rust"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
ndarray = "0.15"
num-complex = "0.4"
num-traits = "0.2"
rand="0.8"
rayon = "1.5"
itertools = "0.10"
approx = "0.5"
regex = "1"
lazy_static = "1.4"
thiserror = "1.0"